name: mediflow_mobile
description: Aplicativo Flutter Android educacional do MediFlow.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  checkout_domain: ^0.1.0
  flutter_bloc: ^9.1.1
  drift: ^2.34.4
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  dio: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  drift_dev: ^2.34.6
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
